### PR TITLE
Script to check - and manually fix - pset definition data

### PR DESCRIPTION
**Pull request by aothms**
See https://github.com/buildingSMART/ifc-gherkin-rules/issues/198

### CODE REVIEW

**Comment by aothms** [comment]
The diff is a bit hard to read. I recommend checking out locally and doing:

    git diff --color-words='\w+' HEAD~ HEAD

**Comment by Ghesselink** [comment]
Checked the code locally. (by pasting the code into the `pse001` testfile folder to only check that rule; there must be a better way of doing that). In `main`
image

In [tfk-pset-data-fixes](https://github.com/buildingSMART/ifc-gherkin-rules/tree/tfk-pset-data-fixes) 
image

Seems good :-) 

For the rest, are we missing something in IFC4X3 as well? With some small tweaks in `check_pset_definitions.py`, I get the following : 
image
So wrong definitions for `IfcBuildingElementProxy`, `IfcRailwayPart` and `IfcReferent`.
However, for example `Track` for IfcRailwayPart should be fine I'd say .. 

IFC4 and 2X3 seem fine now indeed. 
```

import ast
import csv
import glob
import os
import ifcopenshell
import pandas as pd

w = ifcopenshell.ifcopenshell_wrapper

known_ptype_issues = ('IfcAnnotation', 'IfcDiscreteAccessory', 'IfcMaterial')

results = []

for fn in glob.glob('**/pset_definitions.csv', recursive=True):
    found = False
    schema = fn.split(os.sep)[-2].lower()
    print(f"Checking for schema {schema}")
    S = w.schema_by_name(schema)
    
    with open(fn, newline='') as csvfile:
        items = list(csv.DictReader(csvfile, delimiter=','))

    for item in items:
        for ent in ast.literal_eval(item['applicable_entities']):
            ptype = None
            if '/' in ent:
                ent, ptype = ent.split('/')
            assert S.declaration_by_name(ent)
            if ptype is not None:
                if ent not in known_ptype_issues:
                    predefined_type_attr = [a for a in S.declaration_by_name(ent).all_attributes() if a.name() == 'PredefinedType']
                    if predefined_type_attr:
                        enumeration_items = predefined_type_attr[0].type_of_attribute().declared_type().enumeration_items()
                        if ptype not in enumeration_items:
                            found = True
                            results.append({'Schema': schema, 'Entity': ent, 'Invalid PredefinedType': ptype})
    if not found:
        results.append({'Schema': schema, 'Entity': None, 'Invalid PredefinedType': 'No invalid definition found'})

print(pd.DataFrame(results).to_markdown(index=False))

        print("No invalid pset found for {ptype}")
```

**Comment by Ghesselink** [comment]
My mistake. I checked `4x3` instead of `4x3_add2`

`S = w.schema_by_name({'ifc4x3': 'ifc4x3_add2'}.get(schema, schema))`

**Review by Ghesselink — APPROVED** [review]

**Comment by evandroAlfieri** [comment]
Fix https://github.com/buildingSMART/ifc-gherkin-rules/issues/198

**Pull request merged**
