### PR TITLE
VAL-354

### PR DESCRIPTION
**Pull request by JTurbakiewicz**

### CODE REVIEW

**Comment by aothms** [comment]
The name inside the feature is still called "Feature: PSE001 - IfcPropertySet validation"

**Comment by JTurbakiewicz** [comment]
@aothms, good spot, thank you and sorry. I didn't add the change to the file after renaming, my bad.

**Comment by evandroAlfieri** [comment]
@aothms @Ghesselink can be merged?

**Review by Ghesselink — APPROVED** [review]
Just ran it locally, it looks excellent. Haven't looked a lot at this rule, but can totally understand why the error occurs.
The only small thing I could foresee is some hefty db memory use in case the list of acceptable values gets long. 
Screenshot 2024-04-12 at 14 56 34

**Pull request merged**
