### PR TITLE
include ifc4x3_add2

### PR DESCRIPTION
**Pull request by Ghesselink**
https://github.com/buildingSMART/ifc-gherkin-rules/issues/88

### CODE REVIEW

**Comment by aothms** [comment]
Nothing wrong with this, but at this point the ifcopenshell on your system and on the server doesn't read ADD2 yet. So let's wait a while until we can properly test this.

**Comment by evandroAlfieri** [comment]
@Ghesselink as per the comment in VAl-216, maybe we can use this PR to "clean up" all non-4X3_ADD2 given

**Comment by Ghesselink** [comment]
@evandroAlfieri 

The files have been modified to ensure that only the IFC4X3_ADD2 version is permitted for IFC4X3. This update includes the relevant test files.

IfcOpenShell doesn't read IFC4X3_ADD2 yet, hence the checks are failing.

**Comment by aothms** [comment]
There are new ifcopenshell builds now that support ADD2. https://github.com/IfcOpenBot/IfcOpenShell/commit/f8b09b35252fb6db84742b534aceec6b8d89a2e7#commitcomment-129970915 So when you resolve the merge conflicts we can merge this in. The validation service also supports ADD2 now.

**Comment by Ghesselink** [comment]
Outdated due to 
https://github.com/buildingSMART/ifc-gherkin-rules/pull/114

**Pull request closed without merging**
